// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXBFcLgCRGcQDEQH40vZSl7U31gCvWY7A',
    appId: '1:887325120339:web:f83f73047481ac234b33a6',
    messagingSenderId: '887325120339',
    projectId: 'cleaner-a3d0c',
    authDomain: 'cleaner-a3d0c.firebaseapp.com',
    storageBucket: 'cleaner-a3d0c.appspot.com',
    measurementId: 'G-42G2FQX9LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgodcTgF8U4z4yN12hKfWbo5IsWgScPCc',
    appId: '1:887325120339:android:204f0a90ea4ef0d74b33a6',
    messagingSenderId: '887325120339',
    projectId: 'cleaner-a3d0c',
    storageBucket: 'cleaner-a3d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt8OY2lgm55xusKE-rSAhQeQOaiu8vjp0',
    appId: '1:887325120339:ios:41064584cdf9e0f04b33a6',
    messagingSenderId: '887325120339',
    projectId: 'cleaner-a3d0c',
    storageBucket: 'cleaner-a3d0c.appspot.com',
    iosBundleId: 'com.example.cleaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt8OY2lgm55xusKE-rSAhQeQOaiu8vjp0',
    appId: '1:887325120339:ios:664fe43f096470a04b33a6',
    messagingSenderId: '887325120339',
    projectId: 'cleaner-a3d0c',
    storageBucket: 'cleaner-a3d0c.appspot.com',
    iosBundleId: 'com.example.cleaner.RunnerTests',
  );
}
